### ISSUE TITLE
[Feature Request] Retrieve Snyk Organization slug

### ISSUE THREAD

**Issue by johnjelinek** [lendi-au/terraform-provider-snyk#65]
### Terraform Version
```shell
terraform -v
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.44.0
+ provider registry.terraform.io/hashicorp/vault v3.11.0
+ provider registry.terraform.io/lendi-au/snyk v0.2.0
```

### Affected Resource(s)
- `snyk_organization`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "snyk_organization" "snyk_orgs" {
  for_each = local.orgs
  name     = each.value.name
}

output "snyk_orgs" {
  description = "Snyk Organizations"
  value       = snyk_organization.snyk_orgs
}
```

### Expected Behavior
Output should show more than just `name`

### Actual Behavior

Only a list of `name`s were returned. I see in the code, the `Organization` struct fetches the slug from the API:
https://github.com/lendi-au/terraform-provider-snyk/blob/a70b4a8a22f45296ce0cf18c934f21dee4c2dfc3/snyk/api/organization.go#L9-L15

**Comment by johnjelinek** [comment]
@paxmarc: I see your release [is failing](https://github.com/lendi-au/terraform-provider-snyk/actions/runs/4169404308/jobs/7217325477#step:6:74). Perhaps there needs to be a `tty -s` prefixed to a command in your build pipeline.

**Comment by paxmarc** [comment]
Yep - I'm working through the errors. A lot of the actions are quite out of date (a couple of major versions), so bringing them up to date to see if that fixes, before modifying the pipeline itself.

**Comment by johnjelinek** [comment]
Let me know if there's anything I can do to assist. I'm antsy to clear out all the manually maintained `slug`s in my code 😄.

**Comment by paxmarc** [comment]
@johnjelinek New release pushed 🚀
